on:
  push:
    branhes:
      - main
      - testpr

jobs: 
  CreatePullRequest:
    runs-on: ubuntu-latest
    steps: 
      - name: checking out the code
        uses: actions/checkout@v2

      - name: Raise a PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "trying for auto pr"
          token: ${{ secrets.TOKEN_GITHUB }}
          body: this is to show auto pr
          delete-branch: true
          

